rabbitmq_host: "localhost"
rabbitmq_port: 5672
rabbitmq_login: "login"
rabbitmq_password: "pass"
rabbitmq_consumer_queue_name: "data_receiver_queue"
rabbitmq_producer_queue_name: "data_process_queue"
