version: '3'

services:
 
  mongo-db-hostory:
    image: mongo
    container_name: "mongo_db"
    ports:
      - "27010:27017"
    volumes:
      - ./mongo_data/db:/data/db
      - ./mongo_dump/dump:/data/dump


# to restore dump 
# docker exec -it mongodb bash -c "mongorestore --gzip --archive=data/dump/dump.tar.gz"