up_redis:
	docker compose -f docker-compose-redis.yaml up -d

down_redis:
	docker compose -f docker-compose-redis.yaml down

up_mongo:
	docker compose -f docker-compose-mongo.yaml up -d

down_mongo:
	docker compose -f docker-compose-mongo.yaml down