rabbitmq_host: "localhost"
rabbitmq_port: 5672
rabbitmq_login: "login"
rabbitmq_password: "pass"
rabbitmq_consumer_queue_name: "data_process_queue"
mongo_url: "localhost:27017"
mongo_db: "application"
redis_url: "redis://localhost:6379"
