up_gui:
	docker compose -f docker-compose-gui.yaml up -d
down_gui:
	docker compose -f docker-compose-gui.yaml down
	
up_kafka:
	docker compose -f docker-compose.yaml up -d
down_kafka:
	docker compose -f docker-compose.yaml down